name: expresiones
run-name: ¡Estoy aprendiendo expresiones!
on: 
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer

jobs:
  mayor:
    if: ${{inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Correr script
        run: python hola-mundo.py
